name: .NET Core Desktop

on:
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ "main" ]  # 触发构建的分支
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]  # 构建配置（Debug 或 Release）

    runs-on: windows-latest  # 使用 Windows 环境

    env:
      Solution_Name: NbtStudio/NbtStudio.csproj  # 替换为你的可执行项目文件名称
      Wap_Project_Directory: publish  # 发布目录

    steps:
      - name: Checkout
        uses: actions/checkout@v4  # 拉取代码
        with:
          submodules: true  # 启用子模块

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4  # 安装 .NET SDK
        with:
          dotnet-version: '6.0.x'  # 设置 .NET 版本

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v2  # 设置 MSBuild

      - name: Restore dependencies
        run: dotnet restore  # 还原 NuGet 包

      - name: Build
        run: dotnet build --configuration ${{ matrix.configuration }} --no-restore  # 构建项目

      - name: Publish as Single File
        run: dotnet publish ${{ env.Solution_Name }} --configuration ${{ matrix.configuration }} --output ${{ env.Wap_Project_Directory }} -p:PublishSingleFile=true -p:IncludeNativeLibrariesForSelfExtract=true -p:RuntimeIdentifier=win-x64  # 发布为单个文件

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4  # 上传构建产物
        with:
          name: SingleFileExe
          path: ${{ env.Wap_Project_Directory }}
